[workspace]
resolver = "3"

members = ["amadeus-node", "client", "http"]

[workspace.package]
version = "1.1.8"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/valentynfaychuk/rs_node"
