[workspace]
resolver = "3"

members = ["core", "client", "http"]

[workspace.dependencies]
ama_core = { path = "core" }
http = { path = "http", package = "dashboard" }

[patch.crates-io]
reed-solomon-simd = { git = "https://github.com/AndersTrier/reed-solomon-simd" } # 3.1.0
