[workspace]
resolver = "3"

members = ["amadeus-utils", "amadeus-runtime", "amadeus-node", "client", "http"]

[workspace.package]
version = "1.2.5"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/valentynfaychuk/rs_node"
