[alias]
node = ["run", "-p", "client", "--bin", "node"]
cli = ["run", "-p", "client", "--bin", "cli"]
test-all = ["test", "--workspace", "--all-targets"]
lint = ["clippy", "--workspace", "--all-targets", "--", "-Dwarnings"]
