[alias]
node = ["run", "-p", "amadeusd", "--bin", "amadeusd", "--release"]
test-all = ["test", "--workspace", "--all-targets", "--no-fail-fast", "--exclude", "amadeusd"]
lint = ["clippy", "--workspace", "--all-targets", "--", "-Dwarnings"]

[net]
git-fetch-with-cli=true
